@"%SystemRoot%\System32\WindowsPowerShell\v1.0\powershell.exe" -NoProfile -InputFormat None -ExecutionPolicy Bypass -Command "iex ((New-Object 
System.Net.WebClient).DownloadString('https://chocolatey.org/install.ps1'))" && SET "PATH=%PATH%;%ALLUSERSPROFILE%\chocolatey\bin"

choco install steam -y
choco install foxitreader -y
choco install git -y
choco install gitkraken -y
choco install paint.net -y
choco install filezilla -y
choco install notepadplusplus -y
choco install 7zip -y
choco install vlc -y
choco install googlechrome -y
choco install dropbox -y
choco install vscode -y
choco install androidstudio -y
choco install beyondcompare -y
choco install miktex -y
choco install texstudio -y
choco install kicad -y
choco install openvpn -y
choco install audacity -y
choco install hxd -y
choco install putty -y
choco install spotify -y
choco install jdk8 -y
choco install etcher -y
choco install hyper -y
choco install putty -y
choco install python3 -y
choco install discord -y
choco install plexmediaserver -y
choco install origin -y
choco install vnc-viewer -y
choco install obs-studio -y
choco install qbittorrent -y
choco install freecad -y
choco install advanced-ip-scanner -y
choco install prusaslicer -y
choco install golang -y
choco install atom -y
