@"%SystemRoot%\System32\WindowsPowerShell\v1.0\powershell.exe" -NoProfile -InputFormat None -ExecutionPolicy Bypass -Command "iex ((New-Object
System.Net.WebClient).DownloadString('https://chocolatey.org/install.ps1'))" && SET "PATH=%PATH%;%ALLUSERSPROFILE%\chocolatey\bin"
choco install steam -y -r
choco install foxitreader -y -r
choco install git -y -r
choco install paint.net -y -r
choco install filezilla -y -r
choco install notepadplusplus -y -r
choco install 7zip -y -r
choco install vlc -y -r
choco install googlechrome -y -r
choco install vscode -y -r
choco install androidstudio -y -r
choco install beyondcompare -y -r
choco install miktex -y -r
choco install texstudio -y -r
choco install kicad -y -r
choco install openvpn -y -r
choco install audacity -y -r
choco install hxd -y -r
choco install putty -y -r
choco install spotify -y -r
choco install jdk8 -y -r
choco install etcher -y -r
choco install putty -y -r
choco install python3 -y -r
choco install discord -y -r
choco install plexmediaserver -y -r
choco install origin -y -r
choco install vnc-viewer -y -r
choco install obs-studio -y -r
choco install freecad -y -r
choco install advanced-ip-scanner -y -r
choco install prusaslicer -y -r
choco install blender -y -r
choco install vim -y -r
choco install golang -y -r
choco install microsoft-windows-terminal -y -r
choco install sqLitebrowser -y -r
